version: "3.7"

services:
  app:
    image: tom-calculator/app:latest
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    # TODO: move to Dockerfile
    environment:
      TOM_CONFIG: "/app/config.yml"
      TOM_DATA: "/app/data"
    command: python tom_calculator/main.py
    restart: always
    ports:
      - "18000:80"

  postgres:
    image: tom-calculator/postgres:latest
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    env_file:
        - .env
    volumes:
      - tom-calculator__postgres:/var/lib/postgresql/data
    restart: always
    ports:
        - "18001:5432"

volumes:
    tom-calculator__postgres:
        name: tom-calculator__postgres
