version: "3.7"

services:
  nginx:
    depends_on:
      - app
    image: tom-calculator/nginx:latest
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - "18000:80"

  app:
    depends_on:
      - postgres
    image: tom-calculator/app:latest
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    environment:
      TOM_CONFIG: "/app/config.yml"
      TOM_DATA: "/app/data"
    restart: always
    ports:
      - "18001:8000"

  postgres:
    image: tom-calculator/postgres:latest
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    env_file:
        - ./docker/postgres/.env
    volumes:
      - tom-calculator__postgres:/var/lib/postgresql/data
    restart: always
    ports:
        - "18002:5432"

volumes:
    tom-calculator__postgres:
        name: tom-calculator__postgres
