version: "3.7"

services:
  app:
    image: tom-calculator/app:latest
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    # TODO: move to Dockerfile
    working_dir: /app
    command: python run
    restart: always
    ports:
      - "18000:80"

  postgres:
    image: tom-calculator/postgres:latest
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: tom
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tom
    volumes:
      - tom-calculator__postgres:/var/lib/postgresql/data
    restart: always
    ports:
        - "18001:5432"

volumes:
    tom-calculator__postgres:
        name: tom-calculator__postgres
