version: "3.7"

services:
  # Nginx service available on port 18000
  nginx:
    depends_on:
      - app
    image: tom-calculator/nginx:latest
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - "18000:80"

  # App service available on port 18001 and requires TOM_CONFIG, TOM_DATA variables
  # TOM_CONFIG points to absolute path of configuration file in docker container
  # TOM_DATA points to absolute path of directory with data in docker container
  app:
    depends_on:
      - postgres
    image: tom-calculator/app:latest
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    environment:
      TOM_CONFIG: "/app/config.yml"
      TOM_DATA: "/app/data"
    restart: always
    ports:
      - "18001:8000"

  # Postgres service available on port 18002 and requires variables from .env file
  # On first launch databases are initialized with credentials from .env
  # To recreate data use `docker volume rm tom-calculator__postgres` command
  postgres:
    image: tom-calculator/postgres:latest
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    env_file:
        - ./docker/postgres/.env
    volumes:
      - tom-calculator__postgres:/var/lib/postgresql/data
    restart: always
    ports:
        - "18002:5432"

# On first launch docker volume is created
# To recreate data use `docker volume rm tom-calculator__postgres` command
volumes:
    tom-calculator__postgres:
        name: tom-calculator__postgres
