#!/usr/bin/env bash
psql --dbname postgres --username "postgres" <<-EOSQL
CREATE USER ${TOM_USER} WITH PASSWORD '${TOM_USER_PASSWORD}';
CREATE USER ${TOM_USER_TEST} WITH PASSWORD '${TOM_USER_TEST_PASSWORD}';
CREATE DATABASE ${TOM_DBNAME} WITH OWNER = ${TOM_USER};
CREATE DATABASE ${TOM_DBNAME_TEST} WITH OWNER = ${TOM_USER_TEST};
EOSQL
